import type { TextLayer,TextLayerAttribute } from "../_lib/editor-types";
import FontFamilyPicker from "./font-picker";
import TextStyles from "./text-styles";
interface Props{ textSet:TextLayer; handleAttributeChange:(id:number,attribute:TextLayerAttribute,value:string|number)=>void; }
export default function TextCustomizer({textSet,handleAttributeChange}:Props){const change=(attribute:TextLayerAttribute,value:string|number)=>handleAttributeChange(textSet.id,attribute,value);return <div className="space-y-5">
  <TextStyles key={textSet.id} layer={textSet}/>
  <div><label className="editor-label" htmlFor={`text-${textSet.id}`}>Text</label><input id={`text-${textSet.id}`} className="editor-input" value={textSet.text} onChange={e=>change("text",e.target.value)} placeholder="Say something bold"/></div>
  <div className="grid grid-cols-[minmax(0,1fr)_76px] gap-3"><FontFamilyPicker attribute="fontFamily" currentFont={textSet.fontFamily} handleAttributeChange={(attribute,value)=>change(attribute,value)}/><div><label className="editor-label" htmlFor={`color-${textSet.id}`}>Color</label><input id={`color-${textSet.id}`} type="color" className="h-11 w-full cursor-pointer rounded-xl border border-black/10 bg-[#f8f7fb] p-1.5" value={textSet.color} onChange={e=>change("color",e.target.value)}/></div></div>
  <div><div className="mb-2 flex items-center justify-between"><label className="editor-label !mb-0" htmlFor={`size-${textSet.id}`}>Size</label><output className="text-xs font-medium text-[#6f54e8]">{textSet.fontSize}</output></div><input id={`size-${textSet.id}`} type="range" min="20" max="500" value={textSet.fontSize} onChange={e=>change("fontSize",Number(e.target.value))} className="w-full accent-[#7557ff]"/></div>
  <details className="group rounded-2xl border border-black/[.07] bg-white/60 p-4"><summary className="flex cursor-pointer list-none items-center justify-between text-sm font-medium">More styling <span className="text-lg font-light transition group-open:rotate-45">＋</span></summary><div className="mt-5 space-y-5 border-t border-black/[.06] pt-5">
    <Range id={`weight-${textSet.id}`} label="Weight" value={textSet.fontWeight} min={100} max={900} step={100} onChange={v=>change("fontWeight",v)}/><Range id={`opacity-${textSet.id}`} label="Opacity" value={textSet.opacity} min={0.1} max={1} step={0.05} onChange={v=>change("opacity",v)}/><Range id={`rotation-${textSet.id}`} label="Rotation" value={textSet.rotation} min={-180} max={180} step={1} onChange={v=>change("rotation",v)}/><Range id={`shadow-${textSet.id}`} label="Shadow blur" value={textSet.shadowSize} min={0} max={80} step={1} onChange={v=>change("shadowSize",v)}/>
  </div></details>
  <p className="text-xs leading-5 text-[#7a7480]">Tip: drag text on the image. Use the corner handles to resize and the top handle to rotate.</p>
</div>}
function Range({id,label,value,min,max,step,onChange}:{id:string;label:string;value:number;min:number;max:number;step:number;onChange:(value:number)=>void}){return <div><div className="mb-2 flex justify-between"><label className="text-xs font-medium text-[#716b7a]" htmlFor={id}>{label}</label><output className="text-xs font-medium">{Math.round(value*100)/100}</output></div><input id={id} type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))} className="w-full accent-[#7557ff]"/></div>}
