import Image from "next/image";
import Link from "next/link";
import girl from "@/public/girl.png";

export default function HeroSection() {
  return <section className="relative overflow-hidden pb-20 pt-12 sm:pt-20 lg:pb-28"><div className="absolute -left-28 top-32 h-72 w-72 rounded-full bg-[#ff7fb2]/25 blur-3xl"/><div className="absolute -right-24 top-0 h-80 w-80 rounded-full bg-[#d8ff63]/35 blur-3xl"/><div className="page-shell relative grid items-center gap-14 lg:grid-cols-[1.05fr_.95fr]">
    <div><span className="eyebrow"><span className="h-2 w-2 rounded-full bg-[#7557ff]"/> Your browser is the studio</span><h1 className="mt-7 max-w-3xl text-[clamp(2.5rem,6vw,6.8rem)] font-black leading-[.86] tracking-[-.075em]">Text that sits <span className="relative inline-block text-[#7557ff]">behind<span className="absolute -bottom-1 left-0 -z-10 h-3 w-full -rotate-2 rounded-full bg-[#d8ff63] opacity-80"/></span> the moment.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#625c69] sm:text-xl">Cut out your subject, layer bold typography, and export a polished visual—without leaving your browser.</p><div className="mt-9 flex flex-col gap-4 sm:flex-row sm:items-center"><Link href="/text-behind-image" className="pill-button-primary">Upload an image <span aria-hidden="true">→</span></Link><span className="text-sm font-medium text-[#716b7a]">Free · no watermark · stays on device</span></div><div className="mt-10 flex items-center gap-5 text-xs font-bold uppercase tracking-[.12em] text-[#716b7a]"><span>JPG</span><span className="h-1 w-1 rounded-full bg-[#7557ff]"/><span>PNG</span><span className="h-1 w-1 rounded-full bg-[#7557ff]"/><span>WEBP</span></div></div>
    <div className="relative mx-auto w-full max-w-[580px]"><div className="absolute -left-5 top-20 z-20 -rotate-6 rounded-2xl bg-[#d8ff63] px-4 py-3 text-sm font-black shadow-[4px_4px_0_#17131f]">100% browser magic ✦</div><div className="grain relative overflow-hidden rounded-[2.25rem] border-2 border-[#17131f] bg-[#ded9ff] p-5 shadow-[14px_14px_0_#17131f]"><div className="relative aspect-[4/5] overflow-hidden rounded-[1.5rem] bg-gradient-to-br from-[#ffafca] via-[#aa98ff] to-[#d8ff63]"><div className="absolute inset-x-0 top-[35%] text-center text-[clamp(4rem,9vw,7.5rem)] font-black uppercase leading-none tracking-[-.08em] text-white/90">UNREAL</div><Image src={girl} alt="Creative portrait with text layered behind the subject" fill priority className="z-10 object-cover object-center" sizes="(max-width:1024px) 90vw,40vw"/><div className="absolute bottom-5 left-5 z-20 rounded-full border border-white/30 bg-black/50 px-4 py-2 text-xs font-bold text-white backdrop-blur-md">Made with OverlayIt</div></div></div><div className="absolute -bottom-7 -right-2 z-20 rotate-6 rounded-full bg-[#ff7fb2] px-5 py-4 text-sm font-black text-white shadow-[4px_4px_0_#17131f]">no design skills needed</div></div>
  </div></section>;
}
